# https://nodejs.org/dist/latest-v16.x/docs/api/
FROM node:lts 

WORKDIR /opt/frontend

COPY ./src/frontend . 

RUN rm -rf /opt/frontend/node_modules

RUN usermod --non-unique --uid 1000 www-data \
  && groupmod --non-unique --gid 1000 www-data \
  && chown -R www-data:www-data /opt/frontend


RUN npm install

# Add packages
RUN npm install --save axios vue-axios
# RUN npm install --save dicom.ts

# USER www-data # Causes npm not to work


EXPOSE 8080

