# https://nodejs.org/dist/latest-v16.x/docs/api/
FROM node:lts 

WORKDIR /opt/frontend

COPY ./src/frontend . 

RUN npm install
# RUN npm install axios
# RUN chown -R $APP_USER:$APP_USER /var/www/html/app/frontend
# RUN npm install @bundled-es-modules/axios --save
# RUN yarn add axios
RUN npm install --save axios vue-axios

EXPOSE 8080

