# Generated by Django 3.2.13 on 2022-06-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('modality', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=20)),
                ('customer', models.CharField(max_length=120)),
                ('duration', models.TimeField()),
            ],
        ),
    ]
