# Generated by Django 3.2.13 on 2022-06-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyses',
            name='duration',
        ),
    ]
