# https://nodejs.org/dist/latest-v16.x/docs/api/
FROM node:lts 

WORKDIR /var/www/html/app/frontend

COPY . . 

RUN npm install

# RUN chown -R $APP_USER:$APP_USER /var/www/html/app/frontend

EXPOSE 8000

